BEGIN;

-- ============================================================
-- PICKCLOUD
-- V3 - MIGRACIÓN MULTI-NEGOCIO
-- ============================================================
--
-- Objetivo:
--   Convertir PickCloud en una aplicación multi-negocio
--   utilizando una única base de datos y un único esquema.
--
-- Fecha: 02/09/2026
--
-- IMPORTANTE:
--   Esta migración presupone que V2 ya fue aplicada correctamente.
--
-- ============================================================
-- - Se creó la tabla "negocio" para soportar múltiples negocios.
-- - Se migraron los negocios existentes desde "configuracion_negocio".
-- - El negocio actual se renombró a "Abarrotes Doña Lupe".
-- - Se agregó "id_negocio" a categoria, producto, pedido, venta
--   y reportes para separar la información por negocio.
-- - Los datos existentes (categorías, productos, pedidos, ventas
--   y reportes) fueron asignados al negocio 1.
-- - El SKU dejó de ser único globalmente y ahora es único por negocio.
-- - Las categorías también son únicas dentro de cada negocio.
-- - Se agregaron índices sobre "id_negocio" para mejorar consultas.
-- - Se eliminó "configuracion_negocio", ya que sus datos ahora
--   forman parte de la tabla "negocio".
-- - No se creó una tabla "cliente_negocio", ya que un cliente
--   puede acceder y comprar en cualquier negocio.
--

-- ============================================================
-- 1. CREAR TABLA NEGOCIO
-- ============================================================

CREATE TABLE negocio (
    id_negocio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_usuario_admin INTEGER NOT NULL,

    nombre_comercial VARCHAR(150) NOT NULL,

    slug VARCHAR(150) NOT NULL,

    direccion VARCHAR(255),

    logo_url VARCHAR(500),

    stock_minimo_defecto INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_negocio_usuario_admin
        FOREIGN KEY (id_usuario_admin)
        REFERENCES usuarios(id_usuario),

    CONSTRAINT uq_negocio_usuario_admin
        UNIQUE (id_usuario_admin),

    CONSTRAINT uq_negocio_slug
        UNIQUE (slug),

    CONSTRAINT chk_negocio_stock_minimo
        CHECK (stock_minimo_defecto >= 0)
);


-- ============================================================
-- 2. MIGRAR configuracion_negocio → negocio
-- ============================================================

INSERT INTO negocio (
    id_negocio,
    id_usuario_admin,
    nombre_comercial,
    slug,
    direccion,
    logo_url,
    stock_minimo_defecto
)
SELECT
    id_configuracion,
    id_usuario,
    CASE
        WHEN id_configuracion = 1
            THEN 'Abarrotes Doña Lupe'
        ELSE nombre_comercial
    END,
    CASE
        WHEN id_configuracion = 1
            THEN 'abarrotes-dona-lupe'
        WHEN id_configuracion = 2
            THEN 'mi-negocio'
        ELSE
            'negocio-' || id_configuracion
    END,
    direccion,
    logo_url,
    stock_minimo_defecto
FROM configuracion_negocio;


-- ============================================================
-- 3. AJUSTAR SECUENCIA DE negocio
-- ============================================================

SELECT setval(
    pg_get_serial_sequence('negocio', 'id_negocio'),
    COALESCE((SELECT MAX(id_negocio) FROM negocio), 1),
    true
);


-- ============================================================
-- 4. CATEGORIA
-- ============================================================

ALTER TABLE categoria
ADD COLUMN id_negocio INTEGER;


-- Todos los registros existentes pertenecen al negocio 1
UPDATE categoria
SET id_negocio = 1;


ALTER TABLE categoria
ALTER COLUMN id_negocio SET NOT NULL;


ALTER TABLE categoria
ADD CONSTRAINT fk_categoria_negocio
FOREIGN KEY (id_negocio)
REFERENCES negocio(id_negocio);


-- Una categoría no puede repetirse dentro del mismo negocio
ALTER TABLE categoria
ADD CONSTRAINT uq_categoria_negocio_descripcion
UNIQUE (id_negocio, descripcion);


-- ============================================================
-- 5. PRODUCTO
-- ============================================================

ALTER TABLE producto
ADD COLUMN id_negocio INTEGER;


-- Todos los productos actuales pertenecen al negocio 1
UPDATE producto
SET id_negocio = 1;


ALTER TABLE producto
ALTER COLUMN id_negocio SET NOT NULL;


ALTER TABLE producto
ADD CONSTRAINT fk_producto_negocio
FOREIGN KEY (id_negocio)
REFERENCES negocio(id_negocio);


-- ============================================================
-- 6. CAMBIAR RESTRICCIÓN DEL SKU
-- ============================================================

-- Actualmente SKU es único globalmente:
-- producto_sku_key

ALTER TABLE producto
DROP CONSTRAINT producto_sku_key;


-- Ahora SKU es único solamente dentro de cada negocio
ALTER TABLE producto
ADD CONSTRAINT uq_producto_negocio_sku
UNIQUE (id_negocio, sku);


-- ============================================================
-- 7. PEDIDO
-- ============================================================

ALTER TABLE pedido
ADD COLUMN id_negocio INTEGER;


-- Todos los pedidos existentes pertenecen al negocio 1
UPDATE pedido
SET id_negocio = 1;


ALTER TABLE pedido
ALTER COLUMN id_negocio SET NOT NULL;


ALTER TABLE pedido
ADD CONSTRAINT fk_pedido_negocio
FOREIGN KEY (id_negocio)
REFERENCES negocio(id_negocio);


-- ============================================================
-- 8. VENTA
-- ============================================================

ALTER TABLE venta
ADD COLUMN id_negocio INTEGER;


-- Todas las ventas existentes pertenecen al negocio 1
UPDATE venta
SET id_negocio = 1;


ALTER TABLE venta
ALTER COLUMN id_negocio SET NOT NULL;


ALTER TABLE venta
ADD CONSTRAINT fk_venta_negocio
FOREIGN KEY (id_negocio)
REFERENCES negocio(id_negocio);


-- ============================================================
-- 9. REPORTES
-- ============================================================

ALTER TABLE reportes
ADD COLUMN id_negocio INTEGER;


-- Todos los reportes existentes pertenecen al negocio 1
UPDATE reportes
SET id_negocio = 1;


ALTER TABLE reportes
ALTER COLUMN id_negocio SET NOT NULL;


ALTER TABLE reportes
ADD CONSTRAINT fk_reportes_negocio
FOREIGN KEY (id_negocio)
REFERENCES negocio(id_negocio);


-- ============================================================
-- 10. ELIMINAR configuracion_negocio
-- ============================================================

DROP TABLE configuracion_negocio;


-- ============================================================
-- 11. ÍNDICES PARA CONSULTAS MULTI-NEGOCIO
-- ============================================================

CREATE INDEX idx_categoria_negocio
    ON categoria(id_negocio);

CREATE INDEX idx_producto_negocio
    ON producto(id_negocio);

CREATE INDEX idx_pedido_negocio
    ON pedido(id_negocio);

CREATE INDEX idx_venta_negocio
    ON venta(id_negocio);

CREATE INDEX idx_reportes_negocio
    ON reportes(id_negocio);


-- ============================================================
-- 12. VALIDACIONES FINALES
-- ============================================================

-- Debe devolver 2 negocios
SELECT
    id_negocio,
    id_usuario_admin,
    nombre_comercial,
    slug
FROM negocio
ORDER BY id_negocio;


-- Debe devolver 7 categorías para negocio 1
SELECT
    id_negocio,
    COUNT(*) AS total_categorias
FROM categoria
GROUP BY id_negocio
ORDER BY id_negocio;


-- Debe devolver 18 productos para negocio 1
SELECT
    id_negocio,
    COUNT(*) AS total_productos
FROM producto
GROUP BY id_negocio
ORDER BY id_negocio;


-- Debe devolver 4 pedidos para negocio 1
SELECT
    id_negocio,
    COUNT(*) AS total_pedidos
FROM pedido
GROUP BY id_negocio
ORDER BY id_negocio;


-- Debe devolver 7 ventas para negocio 1
SELECT
    id_negocio,
    COUNT(*) AS total_ventas
FROM venta
GROUP BY id_negocio
ORDER BY id_negocio;


-- Debe devolver 3 reportes para negocio 1
SELECT
    id_negocio,
    COUNT(*) AS total_reportes
FROM reportes
GROUP BY id_negocio
ORDER BY id_negocio;


COMMIT;