spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pickcloud
spring.datasource.username=pickcloud
spring.datasource.password=pppc

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
